// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"github.com/mgiaccone/vow"
	"slices"
)

var roleValues = []Role{RoleOwner, RoleAdmin, RoleMember}

var roleParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("owner", "admin", "member")}}.Sanitizing(vow.Trim, vow.Lower)

func RoleValues() []Role { return slices.Clone(roleValues) }

func NewRole(in string) (Role, error) {
	v, err := roleParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Role(v), nil
}

func MustRole(in string) Role {
	v, err := NewRole(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Role) IsValid() bool { return slices.Contains(roleValues, x) }

func (x Role) String() string { return string(x) }

func (x Role) Unwrap() string { return string(x) }

func (x Role) IsZero() bool { return x == Role("") }

func (x Role) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }

func (x Role) MarshalText() ([]byte, error) { return []byte(x), nil }

func (x Role) Value() (driver.Value, error) { return string(x), nil }

func (x *Role) Scan(src any) error {
	if src == nil {
		*x = Role("")
		return nil
	}
	switch v := src.(type) {
	case string:
		*x = Role(v)
	case []byte:
		*x = Role(v)
	default:
		return fmt.Errorf("Role.Scan: unsupported type %T", src)
	}
	return nil
}
