// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
	"fmt"
	"github.com/mgiaccone/vow"
	"time"
)

func NewExpiry(in time.Time) (Expiry, error) {
	v, err := expirySpec.Parse(in)
	if err != nil {
		return Expiry{}, err
	}
	return Expiry{v: v}, nil
}

func MustExpiry(in time.Time) Expiry {
	v, err := NewExpiry(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Expiry) Unwrap() time.Time { return x.v }

func (x Expiry) IsZero() bool { return x == Expiry{} }

func (x Expiry) String() string {
	return fmt.Sprint(x.v)
}

func (x Expiry) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Expiry) MarshalText() ([]byte, error) {
	return x.v.MarshalText()
}
