// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
	"github.com/mgiaccone/vow"
)

var codeSanitizer = vow.Chain(vow.Trim)

func NewCode(in string, k Kind) (Code, error) {
	v, err := codeSpec(k).Sanitizing(codeSanitizer).Parse(in)
	if err != nil {
		return Code{}, err
	}
	return Code{v: v}, nil
}

func MustCode(in string, k Kind) Code {
	v, err := NewCode(in, k)
	if err != nil {
		panic(err)
	}
	return v
}

func GenerateCode(k Kind) Code {
	v, err := NewCode(codeGenerator(), k)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Code) Unwrap() string { return x.v }

func (x Code) IsZero() bool { return x == Code{} }

func (x Code) String() string {
	return x.v
}

func (x Code) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
