// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
	"github.com/mgiaccone/vow"
)

func NewCode(in string, a Kind, b Kind, p2 int, extra ...Kind) (Code, error) {
	v, err := codeSpec(a, b, p2, extra...).Parse(in)
	if err != nil {
		return Code{}, err
	}
	return Code{v: v}, nil
}

func MustCode(in string, a Kind, b Kind, p2 int, extra ...Kind) Code {
	v, err := NewCode(in, a, b, p2, extra...)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Code) Unwrap() string { return x.v }

func (x Code) IsZero() bool { return x == Code{} }

func (x Code) String() string {
	return x.v
}

func (x Code) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
