// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
	"time"
)

func NewCode(in string, at time.Time) (Code, error) {
	v, err := codeSpec(at).Parse(in)
	if err != nil {
		return Code{}, err
	}
	return Code{v: v}, nil
}

func MustCode(in string, at time.Time) Code {
	v, err := NewCode(in, at)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Code) Unwrap() string { return x.v }

func (x Code) IsZero() bool { return x == Code{} }

func (x Code) String() string {
	return x.v
}

func (x Code) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
