// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"database/sql/driver"
	"fmt"
)

func NewCode(in string) (Code, error) {
	v, err := codeSpec.Parse(in)
	if err != nil {
		return Code{}, err
	}
	return Code{v: v}, nil
}

func MustCode(in string) Code {
	v, err := NewCode(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Code) Unwrap() string { return x.v }

func (x Code) IsZero() bool { return x == Code{} }

func (x Code) String() string {
	return x.v
}

func (x Code) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *Code) Scan(src any) error {
	if src == nil {
		*x = Code{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("Code.Scan: unsupported type %T", src)
	}
	return nil
}
