// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"github.com/mgiaccone/vow"
	"slices"
)

var statusValues = []Status{StatusOpen, StatusClosed, StatusMerged}

var statusParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("open", "closed", "merged")}}

func StatusValues() []Status { return slices.Clone(statusValues) }

func NewStatus(in string) (Status, error) {
	v, err := statusParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Status(v), nil
}

func MustStatus(in string) Status {
	v, err := NewStatus(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Status) IsValid() bool { return slices.Contains(statusValues, x) }

func (x Status) String() string { return string(x) }

func (x Status) Unwrap() string { return string(x) }

func (x Status) IsZero() bool { return x == Status("") }
