// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"github.com/mgiaccone/vow"
)

var codeSanitizer = vow.Chain(vow.Trim, vow.Lower)

func NewCode(in string, k Kind) (Code, error) {
	v, err := codeSpec(k).Sanitizing(codeSanitizer).Parse(in)
	if err != nil {
		return Code{}, err
	}
	return Code{v: v}, nil
}

func MustCode(in string, k Kind) Code {
	v, err := NewCode(in, k)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Code) Unwrap() string { return x.v }

func (x Code) IsZero() bool { return x == Code{} }

func (x Code) String() string {
	return x.v
}

func (x Code) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Code) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}

func (x Code) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *Code) Scan(src any) error {
	if src == nil {
		*x = Code{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("Code.Scan: unsupported type %T", src)
	}
	return nil
}
