// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"database/sql/driver"
	"fmt"
)

func NewQuantity(in int) (Quantity, error) {
	v, err := quantitySpec.Parse(in)
	if err != nil {
		return Quantity{}, err
	}
	return Quantity{v: v}, nil
}

func MustQuantity(in int) Quantity {
	v, err := NewQuantity(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Quantity) Unwrap() int { return x.v }

func (x Quantity) IsZero() bool { return x == Quantity{} }

func (x Quantity) String() string {
	return fmt.Sprint(x.v)
}

func (x Quantity) Value() (driver.Value, error) {
	return int64(x.v), nil
}

func (x *Quantity) Scan(src any) error {
	if src == nil {
		*x = Quantity{}
		return nil
	}
	switch v := src.(type) {
	case int64:
		x.v = int(v)
	default:
		return fmt.Errorf("Quantity.Scan: unsupported type %T", src)
	}
	return nil
}
