package main

// sourceTemplateText generates one output file's full source. It never
// redeclares a user's type or const block — those already exist in the
// hand-written source — it only emits the methods, and for enums the
// membership rule and values slice, that make the type a value object or
// an enum.
//
// $ always refers to the root data passed to Execute (see render.go), so
// $.VowQualifier reaches the runtime import qualifier from any nesting
// depth, including inside a range over Sanitizers.
const sourceTemplateText = `// Code generated by vow. DO NOT EDIT.

package {{.Name}}

{{if .AllImports}}import (
{{range .AllImports}}	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{end}}){{end}}
{{range .ValueObjects}}
{{if .ParserVar}}var {{.ParserVar}} = {{.SpecExpr}}.Sanitizing({{range $i, $s := .Sanitizers}}{{if $i}}, {{end}}{{$.VowQualifier}}.{{$s}}{{end}})
{{end}}{{if .SanitizerVar}}var {{.SanitizerVar}} = {{$.VowQualifier}}.Chain({{range $i, $s := .Sanitizers}}{{if $i}}, {{end}}{{$.VowQualifier}}.{{$s}}{{end}})
{{end}}
func New{{.Name}}(in {{.BaseType}}{{.ParamSignature}}) ({{.Name}}, error) {
	v, err := {{if .ParserVar}}{{.ParserVar}}{{else}}{{.SpecExpr}}{{if .SanitizerVar}}.Sanitizing({{.SanitizerVar}}){{end}}{{end}}.Parse(in)
	if err != nil {
		return {{.Name}}{}, err
	}
	return {{.Name}}{ {{.FieldName}}: v }, nil
}

func Must{{.Name}}(in {{.BaseType}}{{.ParamSignature}}) {{.Name}} {
	v, err := New{{.Name}}(in{{if .ParamNames}}, {{.ParamNames}}{{end}})
	if err != nil {
		panic(err)
	}
	return v
}
{{if .HasGenerator}}
func Generate{{.Name}}({{.ParamListSignature}}) {{.Name}} {
	v, err := New{{.Name}}({{.GeneratorFunc}}(){{if .ParamNames}}, {{.ParamNames}}{{end}})
	if err != nil {
		panic(err)
	}
	return v
}
{{end}}

func (x {{.Name}}) Unwrap() {{.BaseType}} { return x.{{.FieldName}} }

func (x {{.Name}}) IsZero() bool { return x == {{.Name}}{} }

func (x {{.Name}}) String() string {
{{if .IsString}}	return x.{{.FieldName}}
{{else}}	return fmt.Sprint(x.{{.FieldName}})
{{end}}}
{{if .HasJSON}}
func (x {{.Name}}) MarshalJSON() ([]byte, error) { return json.Marshal(x.{{.FieldName}}) }
{{end}}
{{if .HasText}}
func (x {{.Name}}) MarshalText() ([]byte, error) {
{{if .IsString}}	return []byte(x.{{.FieldName}}), nil
{{else if .IsOther}}	return x.{{.FieldName}}.MarshalText()
{{else}}	return []byte(x.String()), nil
{{end}}}
{{end}}
{{if .HasSQL}}
func (x {{.Name}}) Value() (driver.Value, error) {
{{if .IsIntFamily}}	return int64(x.{{.FieldName}}), nil
{{else if .IsFloat}}	return float64(x.{{.FieldName}}), nil
{{else}}	return x.{{.FieldName}}, nil
{{end}}}

func (x *{{.Name}}) Scan(src any) error {
	if src == nil {
		*x = {{.Name}}{}
		return nil
	}
	switch v := src.(type) {
{{if .IsString}}	case string:
		x.{{.FieldName}} = v
	case []byte:
		x.{{.FieldName}} = string(v)
{{else if .IsIntFamily}}	case int64:
		x.{{.FieldName}} = {{.BaseType}}(v)
{{else if .IsFloat}}	case float64:
		x.{{.FieldName}} = {{.BaseType}}(v)
{{else if .IsBool}}	case bool:
		x.{{.FieldName}} = v
{{else}}	case {{.BaseType}}:
		x.{{.FieldName}} = v
{{end}}	default:
		return fmt.Errorf("{{.Name}}.Scan: unsupported type %T", src)
	}
	return nil
}
{{end}}
{{end}}
{{range .Enums}}
var {{.ValuesVar}} = []{{.Name}}{ {{range .Members}}{{.ConstName}}, {{end}} }

{{if .Sanitizers}}var {{.ParserVar}} = {{$.VowQualifier}}.Spec[string]{Rules: []{{$.VowQualifier}}.Rule[string]{ {{$.VowQualifier}}.OneOf({{quotedMembers .Members}}) }}.Sanitizing({{range $i, $s := .Sanitizers}}{{if $i}}, {{end}}{{$.VowQualifier}}.{{$s}}{{end}})
{{else}}var {{.ParserVar}} = {{$.VowQualifier}}.Spec[string]{Rules: []{{$.VowQualifier}}.Rule[string]{ {{$.VowQualifier}}.OneOf({{quotedMembers .Members}}) }}
{{end}}
func {{.Name}}Values() []{{.Name}} { return slices.Clone({{.ValuesVar}}) }

func New{{.Name}}(in string) ({{.Name}}, error) {
	v, err := {{.ParserVar}}.Parse(in)
	if err != nil {
		return "", err
	}
	return {{.Name}}(v), nil
}

func Must{{.Name}}(in string) {{.Name}} {
	v, err := New{{.Name}}(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x {{.Name}}) IsValid() bool { return slices.Contains({{.ValuesVar}}, x) }

func (x {{.Name}}) String() string { return string(x) }

func (x {{.Name}}) Unwrap() string { return string(x) }

func (x {{.Name}}) IsZero() bool { return x == {{.Name}}("") }
{{if .HasJSON}}
func (x {{.Name}}) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }
{{end}}
{{if .HasText}}
func (x {{.Name}}) MarshalText() ([]byte, error) { return []byte(x), nil }
{{end}}
{{if .HasSQL}}
func (x {{.Name}}) Value() (driver.Value, error) { return string(x), nil }

func (x *{{.Name}}) Scan(src any) error {
	if src == nil {
		*x = {{.Name}}("")
		return nil
	}
	switch v := src.(type) {
	case string:
		*x = {{.Name}}(v)
	case []byte:
		*x = {{.Name}}(v)
	default:
		return fmt.Errorf("{{.Name}}.Scan: unsupported type %T", src)
	}
	return nil
}
{{end}}
{{end}}
`
