// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"github.com/mgiaccone/vow"
	"slices"
)

var roleValues = []Role{RoleOwner, RoleAdmin, RoleMember}

var roleParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("owner", "admin", "member")}}

func RoleValues() []Role { return slices.Clone(roleValues) }

func NewRole(in string) (Role, error) {
	v, err := roleParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Role(v), nil
}

func MustRole(in string) Role {
	v, err := NewRole(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Role) IsValid() bool { return slices.Contains(roleValues, x) }

func (x Role) String() string { return string(x) }

func (x Role) Unwrap() string { return string(x) }

func (x Role) IsZero() bool { return x == Role("") }
