// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
)

func NewID(in string) (ID, error) {
	v, err := idSpec.Parse(in)
	if err != nil {
		return ID{}, err
	}
	return ID{v: v}, nil
}

func MustID(in string) ID {
	v, err := NewID(in)
	if err != nil {
		panic(err)
	}
	return v
}

func GenerateID() ID {
	v, err := NewID(idGenerator())
	if err != nil {
		panic(err)
	}
	return v
}

func (x ID) Unwrap() string { return x.v }

func (x ID) IsZero() bool { return x == ID{} }

func (x ID) String() string {
	return x.v
}

func (x ID) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
