// Code generated by vow. DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"github.com/mgiaccone/vow"
	"slices"
	"time"
)

var anyNumberParser = anyNumberSpec.Sanitizing(vow.Trim)

func NewAnyNumber(in string) (AnyNumber, error) {
	v, err := anyNumberParser.Parse(in)
	if err != nil {
		return AnyNumber{}, err
	}
	return AnyNumber{v: v}, nil
}

func MustAnyNumber(in string) AnyNumber {
	v, err := NewAnyNumber(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x AnyNumber) Unwrap() string { return x.v }

func (x AnyNumber) IsZero() bool { return x == AnyNumber{} }

func (x AnyNumber) String() string {
	return x.v
}

func (x AnyNumber) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x AnyNumber) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *AnyNumber) Scan(src any) error {
	if src == nil {
		*x = AnyNumber{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("AnyNumber.Scan: unsupported type %T", src)
	}
	return nil
}

var emailParser = emailSpec.Sanitizing(vow.Trim, vow.Lower)

func NewEmail(in string) (Email, error) {
	v, err := emailParser.Parse(in)
	if err != nil {
		return Email{}, err
	}
	return Email{v: v}, nil
}

func MustEmail(in string) Email {
	v, err := NewEmail(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Email) Unwrap() string { return x.v }

func (x Email) IsZero() bool { return x == Email{} }

func (x Email) String() string {
	return x.v
}

func (x Email) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Email) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}

func (x Email) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *Email) Scan(src any) error {
	if src == nil {
		*x = Email{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("Email.Scan: unsupported type %T", src)
	}
	return nil
}

func NewExpiry(in time.Time) (Expiry, error) {
	v, err := expirySpec.Parse(in)
	if err != nil {
		return Expiry{}, err
	}
	return Expiry{v: v}, nil
}

func MustExpiry(in time.Time) Expiry {
	v, err := NewExpiry(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Expiry) Unwrap() time.Time { return x.v }

func (x Expiry) IsZero() bool { return x == Expiry{} }

func (x Expiry) String() string {
	return fmt.Sprint(x.v)
}

func (x Expiry) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Expiry) MarshalText() ([]byte, error) {
	return x.v.MarshalText()
}

func NewQuantity(in int) (Quantity, error) {
	v, err := quantitySpec.Parse(in)
	if err != nil {
		return Quantity{}, err
	}
	return Quantity{v: v}, nil
}

func MustQuantity(in int) Quantity {
	v, err := NewQuantity(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Quantity) Unwrap() int { return x.v }

func (x Quantity) IsZero() bool { return x == Quantity{} }

func (x Quantity) String() string {
	return fmt.Sprint(x.v)
}

func (x Quantity) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Quantity) Value() (driver.Value, error) {
	return int64(x.v), nil
}

func (x *Quantity) Scan(src any) error {
	if src == nil {
		*x = Quantity{}
		return nil
	}
	switch v := src.(type) {
	case int64:
		x.v = int(v)
	default:
		return fmt.Errorf("Quantity.Scan: unsupported type %T", src)
	}
	return nil
}

var typedNumberSanitizer = vow.Chain(vow.Trim)

func NewTypedNumber(in string, t PhoneNumberType) (TypedNumber, error) {
	v, err := typedNumberSpec(t).Sanitizing(typedNumberSanitizer).Parse(in)
	if err != nil {
		return TypedNumber{}, err
	}
	return TypedNumber{v: v}, nil
}

func MustTypedNumber(in string, t PhoneNumberType) TypedNumber {
	v, err := NewTypedNumber(in, t)
	if err != nil {
		panic(err)
	}
	return v
}

func (x TypedNumber) Unwrap() string { return x.v }

func (x TypedNumber) IsZero() bool { return x == TypedNumber{} }

func (x TypedNumber) String() string {
	return x.v
}

func (x TypedNumber) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x TypedNumber) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}

func (x TypedNumber) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *TypedNumber) Scan(src any) error {
	if src == nil {
		*x = TypedNumber{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("TypedNumber.Scan: unsupported type %T", src)
	}
	return nil
}

var phoneNumberTypeValues = []PhoneNumberType{TypeShortCode, TypeLVN}

var phoneNumberTypeParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("shortcode", "lvn")}}.Sanitizing(vow.Trim, vow.Lower)

func PhoneNumberTypeValues() []PhoneNumberType { return slices.Clone(phoneNumberTypeValues) }

func NewPhoneNumberType(in string) (PhoneNumberType, error) {
	v, err := phoneNumberTypeParser.Parse(in)
	if err != nil {
		return "", err
	}
	return PhoneNumberType(v), nil
}

func MustPhoneNumberType(in string) PhoneNumberType {
	v, err := NewPhoneNumberType(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x PhoneNumberType) IsValid() bool { return slices.Contains(phoneNumberTypeValues, x) }

func (x PhoneNumberType) String() string { return string(x) }

func (x PhoneNumberType) Unwrap() string { return string(x) }

func (x PhoneNumberType) IsZero() bool { return x == PhoneNumberType("") }

func (x PhoneNumberType) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }

func (x PhoneNumberType) Value() (driver.Value, error) { return string(x), nil }

func (x *PhoneNumberType) Scan(src any) error {
	if src == nil {
		*x = PhoneNumberType("")
		return nil
	}
	switch v := src.(type) {
	case string:
		*x = PhoneNumberType(v)
	case []byte:
		*x = PhoneNumberType(v)
	default:
		return fmt.Errorf("PhoneNumberType.Scan: unsupported type %T", src)
	}
	return nil
}

var roleValues = []Role{RoleOwner, RoleAdmin, RoleMember}

var roleParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("owner", "admin", "member")}}.Sanitizing(vow.Trim, vow.Lower)

func RoleValues() []Role { return slices.Clone(roleValues) }

func NewRole(in string) (Role, error) {
	v, err := roleParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Role(v), nil
}

func MustRole(in string) Role {
	v, err := NewRole(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Role) IsValid() bool { return slices.Contains(roleValues, x) }

func (x Role) String() string { return string(x) }

func (x Role) Unwrap() string { return string(x) }

func (x Role) IsZero() bool { return x == Role("") }

func (x Role) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }

func (x Role) MarshalText() ([]byte, error) { return []byte(x), nil }

func (x Role) Value() (driver.Value, error) { return string(x), nil }

func (x *Role) Scan(src any) error {
	if src == nil {
		*x = Role("")
		return nil
	}
	switch v := src.(type) {
	case string:
		*x = Role(v)
	case []byte:
		*x = Role(v)
	default:
		return fmt.Errorf("Role.Scan: unsupported type %T", src)
	}
	return nil
}
