// Code generated by vow. DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"github.com/mgiaccone/vow"
	"slices"
	"time"
)

var anyPostalCodeParser = anyPostalCodeSpec.Sanitizing(vow.Trim, vow.Upper)

func NewAnyPostalCode(in string) (AnyPostalCode, error) {
	v, err := anyPostalCodeParser.Parse(in)
	if err != nil {
		return AnyPostalCode{}, err
	}
	return AnyPostalCode{v: v}, nil
}

func MustAnyPostalCode(in string) AnyPostalCode {
	v, err := NewAnyPostalCode(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x AnyPostalCode) Unwrap() string { return x.v }

func (x AnyPostalCode) IsZero() bool { return x == AnyPostalCode{} }

func (x AnyPostalCode) String() string {
	return x.v
}

func (x AnyPostalCode) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x AnyPostalCode) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *AnyPostalCode) Scan(src any) error {
	if src == nil {
		*x = AnyPostalCode{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("AnyPostalCode.Scan: unsupported type %T", src)
	}
	return nil
}

var emailParser = emailSpec.Sanitizing(vow.Trim, vow.Lower)

func NewEmail(in string) (Email, error) {
	v, err := emailParser.Parse(in)
	if err != nil {
		return Email{}, err
	}
	return Email{v: v}, nil
}

func MustEmail(in string) Email {
	v, err := NewEmail(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Email) Unwrap() string { return x.v }

func (x Email) IsZero() bool { return x == Email{} }

func (x Email) String() string {
	return x.v
}

func (x Email) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Email) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}

func (x Email) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *Email) Scan(src any) error {
	if src == nil {
		*x = Email{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("Email.Scan: unsupported type %T", src)
	}
	return nil
}

func NewExpiry(in time.Time) (Expiry, error) {
	v, err := expirySpec.Parse(in)
	if err != nil {
		return Expiry{}, err
	}
	return Expiry{v: v}, nil
}

func MustExpiry(in time.Time) Expiry {
	v, err := NewExpiry(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Expiry) Unwrap() time.Time { return x.v }

func (x Expiry) IsZero() bool { return x == Expiry{} }

func (x Expiry) String() string {
	return fmt.Sprint(x.v)
}

func (x Expiry) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Expiry) MarshalText() ([]byte, error) {
	return x.v.MarshalText()
}

var postalCodeSanitizer = vow.Chain(vow.Trim, vow.Upper)

func NewPostalCode(in string, c Country) (PostalCode, error) {
	v, err := postalCodeSpec(c).Sanitizing(postalCodeSanitizer).Parse(in)
	if err != nil {
		return PostalCode{}, err
	}
	return PostalCode{v: v}, nil
}

func MustPostalCode(in string, c Country) PostalCode {
	v, err := NewPostalCode(in, c)
	if err != nil {
		panic(err)
	}
	return v
}

func (x PostalCode) Unwrap() string { return x.v }

func (x PostalCode) IsZero() bool { return x == PostalCode{} }

func (x PostalCode) String() string {
	return x.v
}

func (x PostalCode) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x PostalCode) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}

func (x PostalCode) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *PostalCode) Scan(src any) error {
	if src == nil {
		*x = PostalCode{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("PostalCode.Scan: unsupported type %T", src)
	}
	return nil
}

func NewQuantity(in int) (Quantity, error) {
	v, err := quantitySpec.Parse(in)
	if err != nil {
		return Quantity{}, err
	}
	return Quantity{v: v}, nil
}

func MustQuantity(in int) Quantity {
	v, err := NewQuantity(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Quantity) Unwrap() int { return x.v }

func (x Quantity) IsZero() bool { return x == Quantity{} }

func (x Quantity) String() string {
	return fmt.Sprint(x.v)
}

func (x Quantity) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Quantity) Value() (driver.Value, error) {
	return int64(x.v), nil
}

func (x *Quantity) Scan(src any) error {
	if src == nil {
		*x = Quantity{}
		return nil
	}
	switch v := src.(type) {
	case int64:
		x.v = int(v)
	default:
		return fmt.Errorf("Quantity.Scan: unsupported type %T", src)
	}
	return nil
}

var countryValues = []Country{CountryUS, CountryCA}

var countryParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("US", "CA")}}.Sanitizing(vow.Trim, vow.Upper)

func CountryValues() []Country { return slices.Clone(countryValues) }

func NewCountry(in string) (Country, error) {
	v, err := countryParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Country(v), nil
}

func MustCountry(in string) Country {
	v, err := NewCountry(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Country) IsValid() bool { return slices.Contains(countryValues, x) }

func (x Country) String() string { return string(x) }

func (x Country) Unwrap() string { return string(x) }

func (x Country) IsZero() bool { return x == Country("") }

func (x Country) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }

func (x Country) Value() (driver.Value, error) { return string(x), nil }

func (x *Country) Scan(src any) error {
	if src == nil {
		*x = Country("")
		return nil
	}
	switch v := src.(type) {
	case string:
		*x = Country(v)
	case []byte:
		*x = Country(v)
	default:
		return fmt.Errorf("Country.Scan: unsupported type %T", src)
	}
	return nil
}

var roleValues = []Role{RoleOwner, RoleAdmin, RoleMember}

var roleParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("owner", "admin", "member")}}.Sanitizing(vow.Trim, vow.Lower)

func RoleValues() []Role { return slices.Clone(roleValues) }

func NewRole(in string) (Role, error) {
	v, err := roleParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Role(v), nil
}

func MustRole(in string) Role {
	v, err := NewRole(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Role) IsValid() bool { return slices.Contains(roleValues, x) }

func (x Role) String() string { return string(x) }

func (x Role) Unwrap() string { return string(x) }

func (x Role) IsZero() bool { return x == Role("") }

func (x Role) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }

func (x Role) MarshalText() ([]byte, error) { return []byte(x), nil }

func (x Role) Value() (driver.Value, error) { return string(x), nil }

func (x *Role) Scan(src any) error {
	if src == nil {
		*x = Role("")
		return nil
	}
	switch v := src.(type) {
	case string:
		*x = Role(v)
	case []byte:
		*x = Role(v)
	default:
		return fmt.Errorf("Role.Scan: unsupported type %T", src)
	}
	return nil
}
