// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
	"github.com/mgiaccone/vow"
	"slices"
)

var emailParser = emailSpec.Sanitizing(vow.Trim, vow.Lower)

func NewEmail(in string) (Email, error) {
	v, err := emailParser.Parse(in)
	if err != nil {
		return Email{}, err
	}
	return Email{v: v}, nil
}

func MustEmail(in string) Email {
	v, err := NewEmail(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Email) Unwrap() string { return x.v }

func (x Email) IsZero() bool { return x == Email{} }

func (x Email) String() string {
	return x.v
}

func (x Email) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

var roleValues = []Role{RoleOwner, RoleAdmin, RoleMember}

var roleParser = vow.Spec[string]{Rules: []vow.Rule[string]{vow.OneOf("owner", "admin", "member")}}.Sanitizing(vow.Trim, vow.Lower)

func RoleValues() []Role { return slices.Clone(roleValues) }

func NewRole(in string) (Role, error) {
	v, err := roleParser.Parse(in)
	if err != nil {
		return "", err
	}
	return Role(v), nil
}

func MustRole(in string) Role {
	v, err := NewRole(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Role) IsValid() bool { return slices.Contains(roleValues, x) }

func (x Role) String() string { return string(x) }

func (x Role) Unwrap() string { return string(x) }

func (x Role) IsZero() bool { return x == Role("") }

func (x Role) MarshalJSON() ([]byte, error) { return json.Marshal(string(x)) }
