// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
)

func NewHandle(in string) (Handle, error) {
	v, err := sharedSpec.Parse(in)
	if err != nil {
		return Handle{}, err
	}
	return Handle{v: v}, nil
}

func MustHandle(in string) Handle {
	v, err := NewHandle(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Handle) Unwrap() string { return x.v }

func (x Handle) IsZero() bool { return x == Handle{} }

func (x Handle) String() string {
	return x.v
}

func (x Handle) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
