// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"github.com/mgiaccone/vow"
)

var emailParser = emailSpec.Sanitizing(vow.Trim, vow.Lower)

func NewEmail(in string) (Email, error) {
	v, err := emailParser.Parse(in)
	if err != nil {
		return Email{}, err
	}
	return Email{v: v}, nil
}

func MustEmail(in string) Email {
	v, err := NewEmail(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Email) Unwrap() string { return x.v }

func (x Email) IsZero() bool { return x == Email{} }

func (x Email) String() string {
	return x.v
}

func (x Email) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

func (x Email) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}

func (x Email) Value() (driver.Value, error) {
	return x.v, nil
}

func (x *Email) Scan(src any) error {
	if src == nil {
		*x = Email{}
		return nil
	}
	switch v := src.(type) {
	case string:
		x.v = v
	case []byte:
		x.v = string(v)
	default:
		return fmt.Errorf("Email.Scan: unsupported type %T", src)
	}
	return nil
}
