// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
	"github.com/mgiaccone/vow"
)

func NewCode(in string) (Code, error) {
	v, err := codeSpec().Parse(in)
	if err != nil {
		return Code{}, err
	}
	return Code{v: v}, nil
}

func MustCode(in string) Code {
	v, err := NewCode(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Code) Unwrap() string { return x.v }

func (x Code) IsZero() bool { return x == Code{} }

func (x Code) String() string {
	return x.v
}

func (x Code) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }

var emailParser = emailSpec().Sanitizing(vow.Trim, vow.Lower)

func NewEmail(in string) (Email, error) {
	v, err := emailParser.Parse(in)
	if err != nil {
		return Email{}, err
	}
	return Email{v: v}, nil
}

func MustEmail(in string) Email {
	v, err := NewEmail(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Email) Unwrap() string { return x.v }

func (x Email) IsZero() bool { return x == Email{} }

func (x Email) String() string {
	return x.v
}

func (x Email) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
