// Code generated by vow. DO NOT EDIT.

package fixture

import (
	"encoding/json"
)

func NewLabel(in string) (Label, error) {
	v, err := labelSpec.Parse(in)
	if err != nil {
		return Label{}, err
	}
	return Label{v: v}, nil
}

func MustLabel(in string) Label {
	v, err := NewLabel(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Label) Unwrap() string { return x.v }

func (x Label) IsZero() bool { return x == Label{} }

func (x Label) String() string {
	return x.v
}

func (x Label) MarshalJSON() ([]byte, error) { return json.Marshal(x.v) }
