// Code generated by vow. DO NOT EDIT.

package fixture

func NewToken(in string) (Token, error) {
	v, err := tokenSpec.Parse(in)
	if err != nil {
		return Token{}, err
	}
	return Token{v: v}, nil
}

func MustToken(in string) Token {
	v, err := NewToken(in)
	if err != nil {
		panic(err)
	}
	return v
}

func (x Token) Unwrap() string { return x.v }

func (x Token) IsZero() bool { return x == Token{} }

func (x Token) String() string {
	return x.v
}

func (x Token) MarshalText() ([]byte, error) {
	return []byte(x.v), nil
}
